# Generated by Django 5.2.8 on 2025-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_deportistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('deportistas', models.ManyToManyField(related_name='deportes', to='gestion_deportistas.deportista')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
